name: Seunghyun's Blog
description: Blogging about stuffs
meta_description: "Seunghyun's Blog, Blogging about stuffs"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'https://seunghyun-lee.github.io/'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://seunghyun-lee.github.io/'
author:         'Your Name'
